[project]
name = "todo-api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
<<<<<<< HEAD
dependencies = []
=======
dependencies = [
    "fastapi>=0.128.0",
    "pydantic>=2.12.5",
    "tortoise-orm>=0.25.3",
    "uvicorn>=0.40.0",
]
>>>>>>> dev
